Numpy - Covering from basics to advanced methods in Numppy.

# Numpy - Covering from basics to advanced methods in Numppy.Why Numpy ?....Numpy is Faster...

In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(type(a))
print(a.dtype)
print("Hello World...from Numpy")

<class 'numpy.ndarray'>
int32
Hello World...from Numpy


# Dimensions

In [4]:
a = np.array([[1,2,4],[4,5,6]])
print(a.ndim)

b = np.array([[1,2,3],[4,5,6]])
#b.ndim

## If we concatenate a list of 2d arrays you get ***3d arrays***
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]]])
print(c.ndim)
print(c.shape)
print(c[0][1][2])
print(c.shape[0])
print(c.shape[1])
print(c.shape[2])

A = np.array([2])
print(A.ndim)
B = np.array(2)
print(B.ndim)   #Because when the number are passed as list/tuple, then only they are considered as Array of Particular Dimension
print(f"Size is:{c.size}")
print(f"Total bytes:{c.nbytes}")

2
3
(2, 3, 3)
6
2
3
3
1
0
Size is:18
Total bytes:72


# Some Basic Operations

In [8]:
a = np.array([range(i,i+3) for i in [2,4,6]])
print(a)
#   A 3*5 floating array filled with zeros : 
a = np.zeros((3,5),dtype=int)
print(a)
#   length-10 integer array filled with zero : 
a = np.zeros(10,dtype=float)
print(a)
#   Array filled with 3.14 : 
a = np.full((3,2),3.14)
print(a)
#   Starting at 0 ending at 20, stepping by 2 : 
a = np.arange(0,20,2)
print(a)
#   An array of five values evenly spaced between 0 & 1 :
a = np.random.random((3,3))
print(a)
#   Identity Matrix:
a = np.eye(3)
print(a)
#   Elements from 0 to 9 in a very shuffled
a = np.random.permutation(np.arange(10))
print(a)
#   Returning values between 20 and 30
a = np.random.randint(20,30)
print(a)
print(type(a))

a = np.random.rand(1000)
print(a)   #Random numbers from 0 to 1

a = np.random.rand(2,3,4,2)
print(a)
"""It contains two arrays that are 3-dimensional, each dimensional array has 3-dimensional,
 each dimensional array has 4-dimensional and one dimensional array has 2 elements in it.
"""

a = np.arange(100).reshape(4,25)
print(a)
a = np.arange(100).reshape(4,5,5)
print(a)

"""
ARRANGING, RESHAPING & SHAPING THE ARRAYS.
"""
x1 = np.random.randint(10,size=6)
print(x1)

[[2 3 4]
 [4 5 6]
 [6 7 8]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[3.14 3.14]
 [3.14 3.14]
 [3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[[0.21379158 0.30611153 0.81227026]
 [0.44642312 0.072738   0.61422503]
 [0.08874277 0.68541663 0.4203681 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[7 8 4 1 2 6 0 9 3 5]
26
<class 'int'>
[0.24211657 0.68673033 0.56827575 0.13535836 0.46551545 0.16177394
 0.93953398 0.89640239 0.05679098 0.64855278 0.61162448 0.07628839
 0.43970322 0.03310775 0.98601722 0.33384919 0.80375979 0.70561463
 0.20698838 0.38197995 0.75037247 0.22800481 0.87190414 0.78468126
 0.77441986 0.37811096 0.63876824 0.66305321 0.2938294  0.55148928
 0.10946766 0.84036409 0.11107047 0.87285984 0.22833134 0.6479638
 0.34911714 0.68312908 0.79087768 0.8745866  0.4333677  0.26056832
 0.04328053 0.60538172 0.80630257 0.2558449  0.64906508 0.56872813
 0.90622867 0.28570767 0.06777863 0.49417533 0.00225168 0.44928998
 0.76132956 0.36626473 0.25513474 0.79641

# SLICING:

In [91]:
A = np.arange(100)
b = A[3:10]
print(b)
 
"""By slicing  ***b[0] = -1200*** through this method, b is not a copy but is accssing same memory"""

b = A[3:10].copy()
b[0] = -1200 # It's a different copy view
print(A)

print(A[::5])
print(A[::-5])

"""
Finding out the index of a element in a numpy array:
"""
idx = np.argwhere(A == 9)[0][0]
print(f"Index is:{idx}")

A = np.round(10*np.random.rand(5,4))
print(A)
print(A[1,:])  #   for accessing second row(row should be one and all the coumns)
print(A[:,1])
print(A[1:3,2:4])
print(A.T)

"""Importing Linear Algebra """
import numpy.linalg as la
print(la.inv(np.random.rand(3,3)))

A.sort(axis = 1)
print(A)
A.sort(axis = 0)
print(A)

[3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[99 94 89 84 79 74 69 64 59 54 49 44 39 34 29 24 19 14  9  4]
Index is:9
[[0. 6. 5. 0.]
 [2. 3. 5. 1.]
 [4. 0. 1. 1.]
 [5. 7. 3. 6.]
 [5. 3. 7. 7.]]
[2. 3. 5. 1.]
[6. 3. 0. 7. 3.]
[[5. 1.]
 [1. 1.]]
[[0. 2. 4. 5. 5.]
 [6. 3. 0. 7. 3.]
 [5. 5. 1. 3. 7.]
 [0. 1. 1. 6. 7.]]
[[-1.07414763 -1.15682401  1.54521213]
 [-0.00533051  3.91822582 -0.99493048]
 [ 1.56412264 -2.25255133  0.35175215]]
[[0. 0. 5. 6.]
 [1. 2. 3. 5.]
 [0. 1. 1. 4.]
 [3. 5. 6. 7.]
 [3. 5. 7. 7.]]
[[0. 0. 1. 4.]
 [0. 1. 3. 5.]
 [1. 2. 5. 6.]
 [3. 5. 6. 7.]
 [3. 5. 7. 7.]]


In [5]:
??np.argwhere

Signature: np.argwhere(a)
Source:   
@array_function_dispatch(_argwhere_dispatcher)
def argwhere(a):
    """
    Find the indices of array elements that are non-zero, grouped by element.

    Parameters
    ----------
    a : array_like
        Input data.

    Returns
    -------
    index_array : (N, a.ndim) ndarray
        Indices of elements that are non-zero. Indices are grouped by element.
        This array will have shape ``(N, a.ndim)`` where ``N`` is the number of
        non-zero items.

    See Also
    --------
    where, nonzero

    Notes
    -----
    ``np.argwhere(a)`` is almost the same as ``np.transpose(np.nonzero(a))``,
    but produces a result of the correct shape for a 0D array.

    The output of ``argwhere`` is not suitable for indexing arrays.
    For this purpose use ``nonzero(a)`` instead.

    Examples
    --------
    >>> x = np.arange(6).reshape(2,3)
    >>> x
    array([[0, 1, 2],
           [3, 4, 5]])
    >>> np.argwhere(x>1)
    array([[0, 2],
       

# MASKING:

In [13]:
A = np.arange(100)
B = A[[3,5,6]]
print(B)

B = A[(A<40) & (A>30)]
print(B)
"""
&,|,~ ....... are used when left side and right side cna be arrays.
and,or,not ......are used when both side have single objects or bollean value containing True or False.
"""

[3 5 6]
[31 32 33 34 35 36 37 38 39]


'\n&,|,~ ....... are used when left side and right side cna be arrays.\nand,or,not ......are used when both side have single objects or bollean value containing True or False.\n'

# UFUNC'S: Remove slow Python Loops

In [42]:
# Absolute Value:
x = np.array([[-2,-1,0,1,2]])
print(np.abs(x))
# Absolute also returns the magnitude of Imaginary Numbers:
x = np.array([3-4j,4-3j,2+0j])
print(np.absolute(x))

#   Triggnometric Function
theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))

#   Inverse Trignomrteric Function:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))

#   Exponents and Logarithms
x = [1,2,3]
print(x)
print(np.exp(x))
print(np.exp2(x))
print(np.power(3,x))

x = [1,2,4,10]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

"""
When x is very small, thes func. gives more precise values.....
"""
x = [0,0.001,0.01,0.1]
print(np.expm1(x))
print(np.log1p(x))

# Some special Ufuncs: 

from scipy import special
#   Gamma Function: 
x = [1,5,10]
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x,2))

#   Error  Function (Integral of Gaussain) : it's compliment and it's inverse....
x = np.array([0,0.3,0.7,1.0])
print(special.erf(x))
print(special.erfc(x))
print(special.erfinv(x))

#   Specifying the Output:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
print(y)
y = np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

#   Aggreagates: 
x = np.arange(1,6)
print(np.add.reduce(x))
print(np.multiply.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))


# Outer Products: 
x = np.arange(1,6)
print(np.multiply.outer(x,x))

[[2 1 0 1 2]]
[5. 5. 2.]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]
[0.         0.69314718 1.38629436 2.30258509]
[0.         1.         2.         3.32192809]
[0.         0.30103    0.60205999 1.        ]
[0.         0.0010005  0.01005017 0.10517092]
[0.         0.0009995  0.00995033 0.09531018]
[1.0000e+00 2.4000e+01 3.6288e+05]
[ 0.          3.17805383 12.80182748]
[0.5        0.03333333 0.00909091]
[0.         0.32862676 0.67780119 0.84270079]
[1.         0.67137324 0.32219881 0.15729921]
[0.         0.27246271 0.73286908        inf]
[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


# BROADCASTING: Simply a set of rules on applying Binary Ufuncs to on arrays of different sizes......

In [55]:
A = np.round(10*np.random.rand(2,3))
print(A+3)
print(A+(np.arange(2).reshape(2,1)))

B = np.round(10*np.random.rand(2,2))
print(B)
C = np.hstack((A,B))
print(C)

#   Splittting of Arrays: 
grid = np.arange(16).reshape((4,4))
print(grid)
uppper,lower = np.vsplit(grid,[2])
left,rightz  = np.hsplit(grid,[2])

#   Comparison Operator as Ufuncs:
"""
Numpy also implements comparison operators such as <(less than) and >(grater than) 
as element-wise Ufuns. The result of the copmoarison operator is always an array with a boolean
data type.....
"""
x = np.array([1,2,3,4,5])
print(x<3)
print(x>3)
print(x<=3)
print(x>=3)
print(x!=3)
print(x==3)

"""
It is also possible to do an element-by-element comparison of two arrays
and to include compound expressions...
"""
print((2*x) == (x**2))

[[12. 12. 10.]
 [ 4. 13. 10.]]
[[ 9.  9.  7.]
 [ 2. 11.  8.]]
[[6. 2.]
 [4. 5.]]
[[ 9.  9.  7.  6.  2.]
 [ 1. 10.  7.  4.  5.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ True  True False False False]
[False False False  True  True]
[ True  True  True False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]
[False  True False False False]


# Working with Boolean Arrays:

In [96]:
S = np.array([[5,0,3,3],
              [7,9,3,5],
              [2,4,7,6]
])

print(np.count_nonzero(S<6))
print(np.sum(S<6))
print(np.sum(S<6,axis=1))   # This counts the number of values less than 6 in each row of the matrix..

#   Any and All
#      Are there any values greater than 8
print(np.any(S>8))
print(np.any(S==1))
#      Are all values less than 0
print(np.all(S<0))
print(np.all(S==7))

#   Boolean Array as Masks:  
print(S<5)
# ...Now to select this values from the array:  
S[S<5]

8
8
[4 2 2]
True
False
False
False
[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]


array([0, 3, 3, 3, 2, 4])

# Fancy Indexing: 

In [123]:
rand = np.random.RandomState(42)
print(type(rand))
x = rand.randint(100,size=10)
print(x)
#   Suppose we want to acccess three different elements: 
print([x[3],x[7],x[2]])
#   Alternate method: by passing array of indices to obtain the same result...
ind = [3,7,2]
print(x[ind])

'''
With fancy indexing the shape of the results reflects the shape of the index arrays raher than
the shape of array being indexed......
'''
ind = np.array([
    [3,7],
    [4,5]
])
print(x[ind])

#   In Multiple dimensions:  
x = np.arange(12).reshape(3,4)
print(x)
row = np.array([0,1,2])
column = np.array([2,1,3])
print(x[row,column])

#   Combined Indexing : 
#      Combining fancy and Simple Indexing:..
print(x[2,[2,0,1]])
#      Combining fancy indexing with Slicing :..
print(x[1:,[2,0,1]])
#      Combining fancy indexing and masking:...
msk = np.array([1,0,1,0],dtype=bool)
x[row[:,np.newaxis],msk]


#   Modifying values with Indexing: 
x = np.arange(10)
i = np.array([2,1,8,4])
x[i]=99
print(x)

x[i]-=10
print(x)

x = np.zeros(10)
x[[0,0]]=[4,6]
print(x)

i = [2,3,3,4,4,4]
x[i]+=1
print(x)

<class 'numpy.random.mtrand.RandomState'>
[51 92 14 71 60 20 82 86 74 74]
[71, 86, 14]
[71 86 14]
[[71 86]
 [60 20]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  5 11]
[10  8  9]
[[ 6  4  5]
 [10  8  9]]
[ 0 99 99  3 99  5  6  7 99  9]
[ 0 89 89  3 89  5  6  7 89  9]
[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 0. 1. 1. 1. 0. 0. 0. 0. 0.]


# Sorting:

In [132]:
x = np.array([2,1,4,3,5])
print(np.sort(x))

#   argsort()- returns the indices of sorted elements:
x = np.array([2,1,4,3,5])
i = np.argsort(x)
print(i)
print(x[i])

#   Partial Sorts:  
x = np.array([7,2,3,1,6,5,4])
print(np.partition(x,3))

x = [[6,3,7],[4,2,3],[4,0,1]]
print(np.partition(X,2,axis=1))

[1 2 3 4 5]
[1 0 3 2 4]
[1 2 3 4 5]
[2 1 3 4 6 5 7]


AxisError: axis 1 is out of bounds for array of dimension 1

# Structured Arrays: 

In [134]:
name = ['Alice','Bob','cathy','Doug']
age = [25,45,37,19]
weight = [65.0,85.5,68.0,61.5]

data = np.dtype({'names':('name','age','weight'),
                'formats':('U10','i4','f8')
                })
print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
